<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    public function getProjectForExternal($id){

        $qb = $this->createQueryBuilder('p')
            ->select('p', 'rip', 'rs', 'c','vp', 'vrip', 'vrs', 'vc')
            ->leftJoin("p.revisionsInProject", "rip")
            ->leftJoin("rip.revisionState", "rs")
            ->leftJoin("rs.component", "c")
            ->leftJoin("p.values", "vp")
            ->leftJoin("c.values", "vc")
            ->leftJoin("rip.values", "vrip")
            ->leftJoin("rs.values", "vrs")
            ->where("p.id = '".$id."'");

        $q = $qb->getQuery();

        return $q->getResult();
    }

}
