<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Query;
use Symfony\Component\Stopwatch\Stopwatch;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    public function getProjectForExternal($id){

        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('p', 'rip', 'rs', 'c')
            ->from("AppBundle:Project", "p")
            ->leftJoin("p.revisionsInProject", "rip")
            ->leftJoin("rip.revisionState", "rs")
            ->leftJoin("rs.component", "c")
            ->where("p.id = '".$id."'");

        $q = $qb->getQuery();

        $result = $q->getSingleResult();

        return $result;
    }

    public function filterFunction(){

        $q = $this
            ->getEntityManager()
            ->createQuery("
        SELECT p, rip, rs, c
        FROM AppBundle:Project p
        LEFT JOIN p.revisionsInProject rip
        LEFT JOIN rip.revisionState rs
        LEFT JOIN rs.component c
        WHERE JSONB_CONTAINS( p.values @> '{\"ACTIVE\": \"1\"}' ) = TRUE
        ");
        var_dump($q->getSQL());

        $result = $q->getResult();

        var_dump($result);

    }

}
